### ISSUE TITLE
Cannot open GUI on MacOS

### ISSUE THREAD

**Issue by kiranvad** [SASfit/SASfit#18]
Hello,
Thanks for open-sourcing this project.
I have trouble fixing the following error thrown when I open the sasfit.command file on my MacOS (Sonoma 14.3) M1 Chip :
`no display name and no $DISPLAY environment variable` (full error stack below)

Do you have any suggestions?

----------------------
```bash
no display name and no $DISPLAY environment variable
    while executing
"load {} Tk"
    ("package ifneeded" script)
    invoked from within
"package require Tk $tcl_version"
    invoked from within
"if {$tcl_version < 8.0} {
    return -code error "tkcon requires at least Tcl/Tk8"
} else {
    package require Tk $tcl_version
}"
    (file "/Users/Downloads/SASfit-0.94.12-macos64/sasfit/lib/Tkcon/tkcon.tcl" line 41)
    invoked from within
"source /Users/Downloads/SASfit-0.94.12-macos64/sasfit/lib/Tkcon/tkcon.tcl"
    ("package ifneeded" script)
    invoked from within
"package require tkcon"
    (file "/Users/Downloads/SASfit-0.94.12-macos64/sasfit/main.tcl" line 34)

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Comment by ibressler** [comment]
Hi kiranvad,
thanks for reporting this!
My first suggestion would be (because you did not mention it), did you install XQuartz on your Mac? You can download its package from here: https://www.xquartz.org/releases/index.html Descriptions on using macports or homebrew for install can be found there too.
Please let us know if this error prevails with XQuartz installed.

**Comment by kiranvad** [comment]
That fixed it. Thanks @ibressler
